spring.application.name=demo
server.port=9090
gemini.api.key=AQ.Ab8RN6IbtVrjQtqnYve1OvmEeXD7Sil-5kM1urHCuQhUHVmR-Q
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
